name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      VIRTUAL_ENV: venv

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            .cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Create virtualenv
        run: |
          virtualenv $VIRTUAL_ENV
          source $VIRTUAL_ENV/bin/activate

      - name: Install linters and tools
        run: |
          pip install pylint mypy black safety pydocstyle
      
      - name: Run black
        run: |
          black . --check --verbose --diff --color >> black_errors.txt || exit 1

      - name: Run pylint
        run: |
          pylint --exit-zero . >> pylint_errors.txt || exit 1

      - name: Run pydocstyle
        run: |
          pydocstyle --ignore-self-only-init . >> pydocstyle_errors.txt || exit 1

      - name: Run mypy
        run: | 
          cd ..
          mypy -p name_of_the_directory >> mypy_errors.txt || exit 1

      - name: Upload error artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-errors
          path: |
            black_errors.txt
            pylint_errors.txt
            pydocstyle_errors.txt
            /home/runner/work/name_of_the_directory/mypy_errors.txt

      - name: Cleanup virtual environment
        run: |
          deactivate || true
          rm -rf venv
